extends: airbnb-base
env:
  node: true
  es2021: true
rules:
  linebreak-style: 0
  no-console: off
  import/extensions: off
"import/no-extraneous-dependencies": ["error", {"devDependencies": true}]